version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: scanexercise_db
    environment:
      POSTGRES_DB: ${DB_NAME:-scanexercise}
      POSTGRES_USER: ${DB_USER:-django}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-yourpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scan_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: scanexercise_backend
    env_file:
      - ./backend/.env
    environment:
      - DB_NAME=${DB_NAME:-scanexercise}
      - DB_USER=${DB_USER:-django}
      - DB_PASSWORD=${DB_PASSWORD:-yourpassword}
      - DB_HOST=db
      - DB_PORT=5432

    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db
    networks:
      - scan_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: scanexercise_frontend
    ports:
      - "5173:80"  # Ánh xạ port 80 của container ra 5173 của host (nhà Đại ca)
    depends_on:
      - backend
    networks:
      - scan_network
    restart: unless-stopped

networks:
  scan_network:
    driver: bridge

volumes:
  postgres_data:
